
image: python:latest
stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - pip install -r requirements.txt
    - echo "依赖安装完毕"

test-code-job1:
  stage: test
  script:
    - echo "If the files are built successfully, test some files with one command:"
    - rake test1

test-code-job2:
  stage: test
  script:
    - echo "If the files are built successfully, test other files with a different command:"
    - rake test2