
image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip






before_script:
  - python3 --version # For debugging
  # - pip install virtualenv
  # - virtualenv venv
  # - source venv/bin/activate


stages:
  - build
  - test
  
  
build-code-job:
  stage: build
  script:
    - echo "111 ok"
    - ls -al
    - echo "222 ok" > a.txt
    # - pip3 install -r requirements.txt
    - echo "222 ok"
    - echo "222 ok" > a.txt

test-code-job1:
  stage: test
  script:
    - python3 main3.py
    - echo "If the files are built successfully, test some files with one command:"
  artifacts:
    paths:
      - dist/*
      - ./dist/*
