
image: python:latest
stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - echo "111 ok"
    - pip install -r requirements.txt
    - echo "222 ok"

test-code-job1:
  stage: test
  script:
    - python main2.py
    - echo "If the files are built successfully, test some files with one command:"
